Concuerror v0.18 (aebd45a) started at 19 Oct 2017 15:43:53
 Options:
  [{after_timeout,infinity},
   {assertions_only,false},
   {assume_racing,false},
   {depth_bound,500},
   {disable_sleep_sets,false},
   {dpor,optimal},
   {entry_point,{kill_running_waiting,test,[]}},
   {exclude_module,[]},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/kill_running_waiting.erl"]},
   {ignore_error,[]},
   {instant_delivery,true},
   {interleaving_bound,infinity},
   {keep_going,true},
   {non_racing_system,[]},
   {print_depth,20},
   {quiet,true},
   {scheduling,round_robin},
   {scheduling_bound_type,none},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,infinity},
   {treat_as_normal,[]},
   {use_receive_patterns,true}]
################################################################################
Interleaving #1
--------------------------------------------------------------------------------
Errors found:
* At step 12 process P.1 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.0.102557325>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.1.102557325>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.2.102557325>,[]])
    in erlang.erl line 2673
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.3.102557325>,[]])
    in erlang.erl line 2673
   5: P: exits normally
   6: P.2: ok = P.1 ! ok
    in kill_running_waiting.erl line 44
   7: P.2: exits normally
   8: P.3: true = erlang:exit(P.1, abnormal)
    in kill_running_waiting.erl line 46
   9: P.3: exits normally
  10: P.4: true = erlang:exit(P.2, abnormal)
    in kill_running_waiting.erl line 48
  11: P.4: exits normally
  12: P.1: exits abnormally (abnormal)
################################################################################
Interleaving #3
--------------------------------------------------------------------------------
Errors found:
* At step 13 process P.1 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.0.102557325>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.1.102557325>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.2.102557325>,[]])
    in erlang.erl line 2673
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.3.102557325>,[]])
    in erlang.erl line 2673
   5: P: exits normally
   6: P.2: ok = P.1 ! ok
    in kill_running_waiting.erl line 44
   7: P.2: exits normally
   8: P.4: true = erlang:exit(P.2, abnormal)
    in kill_running_waiting.erl line 48
   9: P.4: exits normally
  10: P.1: receives message (ok)
    in kill_running_waiting.erl line 42
  11: P.3: true = erlang:exit(P.1, abnormal)
    in kill_running_waiting.erl line 46
  12: P.3: exits normally
  13: P.1: exits abnormally (abnormal)
################################################################################
Interleaving #4
--------------------------------------------------------------------------------
Errors found:
* At step 9 process P.1 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
* At step 12 process P.2 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.0.102557325>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.1.102557325>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.2.102557325>,[]])
    in erlang.erl line 2673
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.3.102557325>,[]])
    in erlang.erl line 2673
   5: P: exits normally
   6: P.2: ok = P.1 ! ok
    in kill_running_waiting.erl line 44
   7: P.3: true = erlang:exit(P.1, abnormal)
    in kill_running_waiting.erl line 46
   8: P.3: exits normally
   9: P.1: exits abnormally (abnormal)
  10: P.4: true = erlang:exit(P.2, abnormal)
    in kill_running_waiting.erl line 48
  11: P.4: exits normally
  12: P.2: exits abnormally (abnormal)
################################################################################
Interleaving #5
--------------------------------------------------------------------------------
Errors found:
* At step 13 process P.2 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.0.102557325>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.1.102557325>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.2.102557325>,[]])
    in erlang.erl line 2673
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.3.102557325>,[]])
    in erlang.erl line 2673
   5: P: exits normally
   6: P.2: ok = P.1 ! ok
    in kill_running_waiting.erl line 44
   7: P.1: receives message (ok)
    in kill_running_waiting.erl line 42
   8: P.1: exits normally
   9: P.3: true = erlang:exit(P.1, abnormal)
    in kill_running_waiting.erl line 46
  10: P.3: exits normally
  11: P.4: true = erlang:exit(P.2, abnormal)
    in kill_running_waiting.erl line 48
  12: P.4: exits normally
  13: P.2: exits abnormally (abnormal)
################################################################################
Interleaving #6
--------------------------------------------------------------------------------
Errors found:
* At step 10 process P.1 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
* At step 13 process P.2 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.0.102557325>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.1.102557325>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.2.102557325>,[]])
    in erlang.erl line 2673
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.3.102557325>,[]])
    in erlang.erl line 2673
   5: P: exits normally
   6: P.2: ok = P.1 ! ok
    in kill_running_waiting.erl line 44
   7: P.1: receives message (ok)
    in kill_running_waiting.erl line 42
   8: P.3: true = erlang:exit(P.1, abnormal)
    in kill_running_waiting.erl line 46
   9: P.3: exits normally
  10: P.1: exits abnormally (abnormal)
  11: P.4: true = erlang:exit(P.2, abnormal)
    in kill_running_waiting.erl line 48
  12: P.4: exits normally
  13: P.2: exits abnormally (abnormal)
################################################################################
Interleaving #7
--------------------------------------------------------------------------------
Errors found:
* At step 10 process P.1 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
* At step 11 process P.2 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.0.102557325>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.1.102557325>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.2.102557325>,[]])
    in erlang.erl line 2673
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.3.102557325>,[]])
    in erlang.erl line 2673
   5: P: exits normally
   6: P.3: true = erlang:exit(P.1, abnormal)
    in kill_running_waiting.erl line 46
   7: P.3: exits normally
   8: P.4: true = erlang:exit(P.2, abnormal)
    in kill_running_waiting.erl line 48
   9: P.4: exits normally
  10: P.1: exits abnormally (abnormal)
  11: P.2: exits abnormally (abnormal)
################################################################################
Interleaving #8
--------------------------------------------------------------------------------
Errors found:
* At step 8 process P.1 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.0.102557325>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.1.102557325>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.2.102557325>,[]])
    in erlang.erl line 2673
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.3.102557325>,[]])
    in erlang.erl line 2673
   5: P: exits normally
   6: P.3: true = erlang:exit(P.1, abnormal)
    in kill_running_waiting.erl line 46
   7: P.3: exits normally
   8: P.1: exits abnormally (abnormal)
   9: P.2: ok = P.1 ! ok
    in kill_running_waiting.erl line 44
  10: P.2: exits normally
  11: P.4: true = erlang:exit(P.2, abnormal)
    in kill_running_waiting.erl line 48
  12: P.4: exits normally
################################################################################
Interleaving #9
--------------------------------------------------------------------------------
Errors found:
* At step 8 process P.1 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
* At step 12 process P.2 exited abnormally
    Reason:
      abnormal
    Stacktrace:
      []
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.0.102557325>,[]])
    in erlang.erl line 2673
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.1.102557325>,[]])
    in erlang.erl line 2673
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.2.102557325>,[]])
    in erlang.erl line 2673
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<kill_running_waiting.3.102557325>,[]])
    in erlang.erl line 2673
   5: P: exits normally
   6: P.3: true = erlang:exit(P.1, abnormal)
    in kill_running_waiting.erl line 46
   7: P.3: exits normally
   8: P.1: exits abnormally (abnormal)
   9: P.2: ok = P.1 ! ok
    in kill_running_waiting.erl line 44
  10: P.4: true = erlang:exit(P.2, abnormal)
    in kill_running_waiting.erl line 48
  11: P.4: exits normally
  12: P.2: exits abnormally (abnormal)
################################################################################
Exploration completed!
################################################################################
Tips:
--------------------------------------------------------------------------------
* Check '--help attributes' for info on how to pass options via module attributes.
* An abnormal exit signal was sent to a process. This is probably the worst thing that can happen race-wise, as any other side-effecting operation races with the arrival of the signal. If the test produces too many interleavings consider refactoring your code.
* Increase '--print_depth' if output/graph contains "...".

################################################################################
Info:
--------------------------------------------------------------------------------
* Automatically instrumented module io_lib
* Instrumented & loaded module kill_running_waiting
* Automatically instrumented module erlang
* You can see pairs of racing instructions (in the report and '--graph') with '--show_races true'
* Continuing after error (-k)

################################################################################
Done at 19 Oct 2017 15:43:54 (Exit status: error)
  Summary: 8 errors, 9/9 interleavings explored
